server:
  port: 9191

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka.clients.NetworkClient: ERROR

spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: 5000
        retries: 1


